# SOME METHOD AND FUNCTION IN PANDAS FOR DATA SCIENCE
---

### Import Library

In [1]:
import numpy as np
import pandas as pd

### Membaca file dan merubah menjadi dataframe

In [5]:
df = pd.read_csv("data/cereal.csv")
# akan menampilkan 5 data awal dan 5 data akhir

### Menampilkan data

In [6]:
df.head()
# menampilkan 5 data awal

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,100% Bran,N,C,70,4,1,130,10.0,5.0,6.0,280.0,FDA_25,3,1.0,0.33,68.402973
1,100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8.0,135.0,FDA_0,3,1.0,1.00,33.983679
2,All-Bran,K,C,70,4,1,260,9.0,7.0,5.0,320.0,FDA_25,3,1.0,0.33,59.425505
3,All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0.0,330.0,FDA_25,3,1.0,0.50,93.704912
4,Almond Delight,R,C,110,2,2,200,1.0,14.0,8.0,NaN,FDA_25,3,1.0,0.75,34.384843

In [7]:
df.tail()
# menampilkan 5 data akhir

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
72,Triples,G,C,110,2,1,250,0.0,21.0,3.0,60.0,FDA_25,3,1.0,0.75,39.106174
73,Trix,G,C,110,1,1,140,0.0,13.0,12.0,25.0,FDA_25,2,1.0,1.00,27.753301
74,Wheat Chex,R,C,100,3,1,230,3.0,17.0,3.0,115.0,FDA_25,1,1.0,0.67,49.787445
75,Wheaties,G,C,100,3,1,200,3.0,17.0,3.0,110.0,FDA_25,1,1.0,1.00,51.592193
76,Wheaties Honey Gold,G,C,110,2,1,200,1.0,16.0,8.0,60.0,FDA_25,1,1.0,0.75,36.187559

In [8]:
df.head(10)
# menampilkan n data dr awal

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,100% Bran,N,C,70,4,1,130,10.0,5.0,6.0,280.0,FDA_25,3,1.00,0.33,68.402973
1,100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8.0,135.0,FDA_0,3,1.00,1.00,33.983679
2,All-Bran,K,C,70,4,1,260,9.0,7.0,5.0,320.0,FDA_25,3,1.00,0.33,59.425505
3,All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0.0,330.0,FDA_25,3,1.00,0.50,93.704912
4,Almond Delight,R,C,110,2,2,200,1.0,14.0,8.0,NaN,FDA_25,3,1.00,0.75,34.384843
5,Apple Cinnamon Cheerios,G,C,110,2,2,180,1.5,10.5,10.0,70.0,FDA_25,1,1.00,0.75,29.509541
6,Apple Jacks,K,C,110,2,0,125,1.0,11.0,14.0,30.0,FDA_25,2,1.00,1.00,33.174094
7,Basic 4,G,C,130,3,2,210,2.0,18.0,8.0,100.0,FDA_25,3,1.33,0.75,37.038562
8,Bran Chex,R,C,90,2,1,200,4.0,15.0,6.0,125.0,FDA_25,1,1.00,0.67,49.120253
9,Bran Flakes,P,C,90,3,0,210,5.0,13.0,5.0,190.0,FDA_25,3,1.00,0.67,53.313813

In [9]:
df.tail(8)
# Menampilkan n data dari akhir

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
69,Total Corn Flakes,G,C,110,2,1,200,0.0,21.0,3.0,35.0,FDA_100,3,1.0,1.00,38.839746
70,Total Raisin Bran,G,C,140,3,1,190,4.0,15.0,14.0,230.0,FDA_100,3,1.5,1.00,28.592785
71,Total Whole Grain,G,C,100,3,1,200,3.0,16.0,3.0,110.0,FDA_100,3,1.0,1.00,46.658844
72,Triples,G,C,110,2,1,250,0.0,21.0,3.0,60.0,FDA_25,3,1.0,0.75,39.106174
73,Trix,G,C,110,1,1,140,0.0,13.0,12.0,25.0,FDA_25,2,1.0,1.00,27.753301
74,Wheat Chex,R,C,100,3,1,230,3.0,17.0,3.0,115.0,FDA_25,1,1.0,0.67,49.787445
75,Wheaties,G,C,100,3,1,200,3.0,17.0,3.0,110.0,FDA_25,1,1.0,1.00,51.592193
76,Wheaties Honey Gold,G,C,110,2,1,200,1.0,16.0,8.0,60.0,FDA_25,1,1.0,0.75,36.187559

In [12]:
df.columns
# menampilakan nama semua kolom pada dataframe

Index(['name', 'mfr', 'type', 'calories', 'protein', 'fat', 'sodium', 'fiber',
       'carbo', 'sugars', 'potass', 'vitamins', 'shelf', 'weight', 'cups',
       'rating'],
      dtype='object')

In [15]:
df.index
# menampilkan index pada dataframe

RangeIndex(start=0, stop=77, step=1)

In [16]:
df.shape
#menampilkan jumlah baris dan kolom pada dataframe
# terdapat 77 data dan 16 kolom

(77, 16)

In [20]:
df.mfr
# memilih salah satu kolom

0     N
1     Q
2     K
3     K
4     R
     ..
72    G
73    G
74    R
75    G
76    G
Name: mfr, Length: 77, dtype: object

In [22]:
df.mfr.head()
# memilih salah satu kolom dan menampilkan 5 data pertama\
# hanya bisa digunakan apabila nama kolom tidakk ada spasinya

0    N
1    Q
2    K
3    K
4    R
Name: mfr, dtype: object

In [24]:
df['mfr'].head()
# cara lain memilih salah satu kolom dan menampilkan 5 data pertama
# bisa digunakan bila nama kolom ada spasinya

0    N
1    Q
2    K
3    K
4    R
Name: mfr, dtype: object

In [28]:
df[['name', 'mfr', 'calories']].head()
# kelebihan kurung siku dapat memilih lebih dari satu kolom

                        name mfr  calories
0                  100% Bran   N        70
1          100% Natural Bran   Q       120
2                   All-Bran   K        70
3  All-Bran with Extra Fiber   K        50
4             Almond Delight   R       110

In [30]:
df[['name', 'mfr', 'calories']][5:10]

# memilih beberapa koom tertentu dan baris tertentu
# contoh 5 sampai 9
# hal ini dinamakan slicing, ada beberqpa cara menggunakan slicing

                      name mfr  calories
5  Apple Cinnamon Cheerios   G       110
6              Apple Jacks   K       110
7                  Basic 4   G       130
8                Bran Chex   R        90
9              Bran Flakes   P        90

### Slicing menggunakan iloc: dan .loc

In [32]:
df.loc[1:4, 'type' : 'fat']

# akan mencslicing berdasarkan nama
# mengambil kolom type sampai sugar dan memilih baris 1 sampai 4

  type  calories  protein  fat
1    C       120        3    5
2    C        70        4    1
3    C        50        4    0
4    C       110        2    2

In [40]:
df.loc[1:4, ['type', 'fat', 'rating']]
# akan mencslicing berdasarkan nama
# mengambil kolom yang terdapat dalam list ['type', 'fat', 'rating'] dan memilih baris 1 sampai 4

  type  fat     rating
1    C    5  33.983679
2    C    1  59.425505
3    C    0  93.704912
4    C    2  34.384843

In [38]:
df.iloc[1:4 , 2:6]

# akan mencslicing berdasarkan index atau suatu integer
# mengambil kolom urutan 2 sampai 6 dan memilih baris 1 sampai 3
# karena berlaku sistem [inklusif , eksklusif]

  type  calories  protein  fat
1    C       120        3    5
2    C        70        4    1
3    C        50        4    0

In [41]:
df.iloc[1:4 , [2, 5, -1]]

# akan mencslicing berdasarkan index atau suatu integer
# mengambil kolom yang terdapat dalam list ['type', 'fat', 'rating'] dan memilih baris 1 sampai 4

  type  fat     rating
1    C    5  33.983679
2    C    1  59.425505
3    C    0  93.704912

###  Menjadikan suatu kolom menjadi index

In [46]:
df = pd.read_csv("data/cereal.csv", index_col='name')
df.head()

# mengubah suatu kolom menjadi index
# kolom yang diubah menjadi index sudah tidak muncul lagi sebagai kolom biasa

,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
name,,,,,,,,,,,,,,,
100% Bran,N,C,70,4,1,130,10.0,5.0,6.0,280.0,FDA_25,3,1.0,0.33,68.402973
100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8.0,135.0,FDA_0,3,1.0,1.00,33.983679
All-Bran,K,C,70,4,1,260,9.0,7.0,5.0,320.0,FDA_25,3,1.0,0.33,59.425505
All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0.0,330.0,FDA_25,3,1.0,0.50,93.704912
Almond Delight,R,C,110,2,2,200,1.0,14.0,8.0,NaN,FDA_25,3,1.0,0.75,34.384843

In [48]:
df.loc['100% Bran':'Wheaties Honey Gold', 'calories':'vitamins']

# karena kolom yang dijadikan index adalah string, maka ketika kita 
# ketika ingin slicing di bagian index harus menggunakan nama
# tidak bisa menggunakan angka integer karena bukan integer
ciri khusu menggunakan .loc adalah menggunakan nama

,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins
name,,,,,,,,,
100% Bran,70,4,1,130,10.0,5.0,6.0,280.0,FDA_25
100% Natural Bran,120,3,5,15,2.0,8.0,8.0,135.0,FDA_0
All-Bran,70,4,1,260,9.0,7.0,5.0,320.0,FDA_25
All-Bran with Extra Fiber,50,4,0,140,14.0,8.0,0.0,330.0,FDA_25
Almond Delight,110,2,2,200,1.0,14.0,8.0,NaN,FDA_25
...,...,...,...,...,...,...,...,...,...
Triples,110,2,1,250,0.0,21.0,3.0,60.0,FDA_25
Trix,110,1,1,140,0.0,13.0,12.0,25.0,FDA_25
Wheat Chex,100,3,1,230,3.0,17.0,3.0,115.0,FDA_25
Wheaties,100,3,1,200,3.0,17.0,3.0,110.0,FDA_25
Wheaties Honey Gold,110,2,1,200,1.0,16.0,8.0,60.0,FDA_25

### DataFrame Summary

In [49]:
df.corr()
# melihat korelasi antar variabel

,calories,protein,fat,sodium,fiber,carbo,sugars,potass,shelf,weight,cups,rating
calories,1.000000,0.019066,0.498610,0.300649,-0.293413,0.257638,0.566533,-0.072063,0.097234,0.696091,0.087200,-0.689376
protein,0.019066,1.000000,0.208431,-0.054674,0.500330,-0.025012,-0.291853,0.563706,0.133865,0.216158,-0.244469,0.470618
fat,0.498610,0.208431,1.000000,-0.005407,0.016719,-0.300003,0.302497,0.200445,0.263691,0.214625,-0.175892,-0.409284
sodium,0.300649,-0.054674,-0.005407,1.000000,-0.070675,0.297687,0.058866,-0.042632,-0.069719,0.308576,0.119665,-0.401295
fiber,-0.293413,0.500330,0.016719,-0.070675,1.000000,-0.380357,-0.138760,0.911528,0.297539,0.247226,-0.513061,0.584160
carbo,0.257638,-0.025012,-0.300003,0.297687,-0.380357,1.000000,-0.471184,-0.365003,-0.192650,0.138467,0.367460,0.088712
sugars,0.566533,-0.291853,0.302497,0.058866,-0.138760,-0.471184,1.000000,0.001414,0.068377,0.455844,-0.048961,-0.763902
potass,-0.072063,0.563706,0.200445,-0.042632,0.911528,-0.365003,0.001414,1.000000,0.385784,0.419933,-0.501607,0.416009
shelf,0.097234,0.133865,0.263691,-0.069719,0.297539,-0.192650,0.068377,0.385784,1.000000,0.190762,-0.335269,0.025159
weight,0.696091,0.216158,0.214625,0.308576,0.247226,0.138467,0.455844,0.419933,0.190762,1.000000,-0.199583,-0.298124
cups,0.087200,-0.244469,-0.175892,0.119665,-0.513061,0.367460,-0.048961,-0.501607,-0.335269,-0.199583,1.000000,-0.203160
rating,-0.689376,0.470618,-0.409284,-0.401295,0.584160,0.088712,-0.763902,0.416009,0.025159,-0.298124,-0.203160,1.000000

In [56]:
df.describe()
# memperlihatkan beberapa metrik deskriptif statistik

,calories,protein,fat,sodium,fiber,carbo,sugars,potass,shelf,weight,cups,rating
count,77.000000,77.000000,77.000000,77.000000,77.000000,76.000000,76.000000,75.000000,77.000000,77.000000,77.000000,77.000000
mean,106.883117,2.545455,1.012987,159.675325,2.151948,14.802632,7.026316,98.666667,2.207792,1.029610,0.821039,42.665705
std,19.484119,1.094790,1.006473,83.832295,2.383364,3.907326,4.378656,70.410636,0.832524,0.150477,0.232716,14.047289
min,50.000000,1.000000,0.000000,0.000000,0.000000,5.000000,0.000000,15.000000,1.000000,0.500000,0.250000,18.042851
25%,100.000000,2.000000,0.000000,130.000000,1.000000,12.000000,3.000000,42.500000,1.000000,1.000000,0.670000,33.174094
50%,110.000000,3.000000,1.000000,180.000000,2.000000,14.500000,7.000000,90.000000,2.000000,1.000000,0.750000,40.400208
75%,110.000000,3.000000,2.000000,210.000000,3.000000,17.000000,11.000000,120.000000,3.000000,1.000000,1.000000,50.828392
max,160.000000,6.000000,5.000000,320.000000,14.000000,23.000000,15.000000,330.000000,3.000000,1.500000,1.500000,93.704912

In [58]:
df.info()
# memperlihatkan tipe data, jumlah data tiap kolom, jumlah kolom dan baris

<class 'pandas.core.frame.DataFrame'>
Index: 77 entries, 100% Bran to Wheaties Honey Gold
Data columns (total 15 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   mfr       77 non-null     object
 1   type      77 non-null     object
 2   calories  77 non-null     int64
 3   protein   77 non-null     int64
 4   fat       77 non-null     int64
 5   sodium    77 non-null     int64
 6   fiber     77 non-null     float64
 7   carbo     76 non-null     float64
 8   sugars    76 non-null     float64
 9   potass    75 non-null     float64
 10  vitamins  77 non-null     object
 11  shelf     77 non-null     int64
 12  weight    77 non-null     float64
 13  cups      77 non-null     float64
 14  rating    77 non-null     float64
dtypes: float64(7), int64(5), object(3)
memory usage: 12.1+ KB

In [64]:
df.mfr.unique()
#memperlihatkan ada berapa kategori unii dalam suatu kolom kategorik

array(['N', 'Q', 'K', 'R', 'G', 'P', 'A'], dtype=object)

In [61]:
df.mfr.value_counts()
# memperlihatkan agregat jumlah data pada kolom kategorik pada masing-masing kategori

K    23
G    22
P     9
Q     8
R     8
N     6
A     1
Name: mfr, dtype: int64

In [66]:
df.nunique()

# memperlijhatkan jumlah data unik pada tiap kolom di dataframe

mfr          7
type         2
calories    11
protein      6
fat          5
sodium      27
fiber       13
carbo       21
sugars      16
potass      35
vitamins     3
shelf        3
weight       7
cups        12
rating      77
dtype: int64

In [67]:
df.rating.mean()
# menampilkan mean dari rating

42.66570498701299

In [69]:
df.rating.median()
# menampilkan median dari rating

40.400208

In [72]:
df.carbo.count()
# menghitungjumlah data kolom tertentu
# hasilnya sama seperti yang ada di df.info

76

### mengetahui data hilang (Missing Value)/Nan

In [78]:
df.isna().sum()
# memperlihatkan data hilang untuk tiap kolom

mfr         0
type        0
calories    0
protein     0
fat         0
sodium      0
fiber       0
carbo       1
sugars      1
potass      2
vitamins    0
shelf       0
weight      0
cups        0
rating      0
dtype: int64

### Drop missing value

In [81]:
df.dropna()

#menghapus baris data yang hilang, terlihat jumlah baris data berkurang

,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
name,,,,,,,,,,,,,,,
100% Bran,N,C,70,4,1,130,10.0,5.0,6.0,280.0,FDA_25,3,1.0,0.33,68.402973
100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8.0,135.0,FDA_0,3,1.0,1.00,33.983679
All-Bran,K,C,70,4,1,260,9.0,7.0,5.0,320.0,FDA_25,3,1.0,0.33,59.425505
All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0.0,330.0,FDA_25,3,1.0,0.50,93.704912
Apple Cinnamon Cheerios,G,C,110,2,2,180,1.5,10.5,10.0,70.0,FDA_25,1,1.0,0.75,29.509541
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Triples,G,C,110,2,1,250,0.0,21.0,3.0,60.0,FDA_25,3,1.0,0.75,39.106174
Trix,G,C,110,1,1,140,0.0,13.0,12.0,25.0,FDA_25,2,1.0,1.00,27.753301
Wheat Chex,R,C,100,3,1,230,3.0,17.0,3.0,115.0,FDA_25,1,1.0,0.67,49.787445
Wheaties,G,C,100,3,1,200,3.0,17.0,3.0,110.0,FDA_25,1,1.0,1.00,51.592193
Wheaties Honey Gold,G,C,110,2,1,200,1.0,16.0,8.0,60.0,FDA_25,1,1.0,0.75,36.187559

### Impute Missing Value

In [82]:
df.fillna(df.mean())

# manampilkan data yang hilang menjadi rata-ratanya (mean)

,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
name,,,,,,,,,,,,,,,
100% Bran,N,C,70,4,1,130,10.0,5.0,6.0,280.000000,FDA_25,3,1.0,0.33,68.402973
100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8.0,135.000000,FDA_0,3,1.0,1.00,33.983679
All-Bran,K,C,70,4,1,260,9.0,7.0,5.0,320.000000,FDA_25,3,1.0,0.33,59.425505
All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0.0,330.000000,FDA_25,3,1.0,0.50,93.704912
Almond Delight,R,C,110,2,2,200,1.0,14.0,8.0,98.666667,FDA_25,3,1.0,0.75,34.384843
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Triples,G,C,110,2,1,250,0.0,21.0,3.0,60.000000,FDA_25,3,1.0,0.75,39.106174
Trix,G,C,110,1,1,140,0.0,13.0,12.0,25.000000,FDA_25,2,1.0,1.00,27.753301
Wheat Chex,R,C,100,3,1,230,3.0,17.0,3.0,115.000000,FDA_25,1,1.0,0.67,49.787445
Wheaties,G,C,100,3,1,200,3.0,17.0,3.0,110.000000,FDA_25,1,1.0,1.00,51.592193
Wheaties Honey Gold,G,C,110,2,1,200,1.0,16.0,8.0,60.000000,FDA_25,1,1.0,0.75,36.187559

In [85]:
df.fillna(df.mean(), inplace=True)

# inplace=True akan membuat data yang hilang pada data asli akan diisi oleh rata-rata

### menyimpan dataframe menjadi CSV

In [87]:
df.to_csv("data/cereal_imputed.csv", index_label='name')

# menyimpan datframe yang sudah dianalisis menjadi csv kembali